### ISSUE TITLE
Latest pandoc version

### ISSUE THREAD

**Issue by stephlocke** [jtilly/R-travis-container-example#2]
Currently, the version in the whitelisted archives is too old for rmarkdown - would you be able to incorporate this into your build?

**Comment by jtilly** [comment]
Take a look at the [Travis config](https://github.com/rstudio/rmarkdown/blob/master/.travis.yml) of the rmarkdown package that uses the containerized infrastructure. [Yihue](https://github.com/yihui) is hosting a compiled recent version of pandoc that can be installed using [this script](https://github.com/yihui/crandalf/blob/master/inst/scripts/install-pandoc).
